#!/bin/sh
set -e

cd `dirname $0`

genchangelog()
{
        echo "$1 ($2) `lsb_release -sc`; urgency=low"
        echo
        git log --since="1 year ago" --date=short --format="  * %s (%h, %cd)" |
                fold --spaces --width 76 | sed 's/^\([^ ]\+\)/    \1/'
        echo
        echo " -- $3  `LANG=C date -R`"
}

pkgversion=$1
test -z "$1" &&
	pkgversion=$(git describe --dirty | cut -c2- |
		sed 's/-\([0-9]\+\)-g\([0-9a-f]\+\)/+\1~\2/' |
		sed 's/\(~[0-9a-f]\+\)-dirty$/-dirty\1/' |
		sed 's/-dirty/~dirty.'`date +%Y%m%d%H%M%S`'/'
	)-$(lsb_release -cs)

pkgmaint=$(echo "`git config user.name` <`git config user.email`>")

changelog=`mktemp`
trap "rm -f '$changelog'; exit 1" INT TERM QUIT

pkgname=d1to2fix
genchangelog "$pkgname" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -f -s dir -t deb -n "$pkgname" -v "$pkgversion" \
	--maintainer "$pkgmaint" \
	--description "Tool to automatically port code from D1 to D2" \
	--url 'https://github.com/sociomantic-tsunami/d1to2fix' \
	--vendor 'Sociomantic Labs GmbH' \
	--license GPLv2 \
	--deb-suggests dmd1 \
	--deb-suggests dmd \
	--deb-changelog "$changelog" \
	../build/last/bin/d1to2fix=/usr/bin/d1to2fix
